# 328 Mapel from DATABASE UTAMA PTS GANJIL 26-27 - TERISI NISN(1).xlsx
MAPEL = [
  ("MP001", "Tamrin Lughoh", "KELAS 1", "AKTIF", "SMP"),
  ("MP002", "Mutholaah", "KELAS 1", "AKTIF", "SMP"),
  ("MP003", "Aqidah", "KELAS 1", "AKTIF", "SMP"),
  ("MP004", "Hadist", "KELAS 1", "AKTIF", "SMP"),
  ("MP005", "Fiqih", "KELAS 1", "AKTIF", "SMP"),
  ("MP006", "Tarikh Islam", "KELAS 1", "AKTIF", "SMP"),
  ("MP007", "Tajwid", "KELAS 1", "AKTIF", "SMP"),
  ("MP008", "Imla", "KELAS 1", "AKTIF", "SMP"),
  ("MP009", "Khot", "KELAS 1", "AKTIF", "SMP"),
  ("MP010", "Mahfudzot", "KELAS 1", "AKTIF", "SMP"),
  ("MP011", "Pendidikan Agama Islam", "KELAS 1", "AKTIF", "SMP"),
  ("MP012", "Bahasa Indonesia", "KELAS 1", "AKTIF", "SMP"),
  ("MP013", "Bahasa Inggris", "KELAS 1", "AKTIF", "SMP"),
  ("MP014", "Matematika", "KELAS 1", "AKTIF", "SMP"),
  ("MP015", "Ilmu Pengetahuan Alam", "KELAS 1", "AKTIF", "SMP"),
  ("MP016", "Ilmu Pengetahuan Sosial", "KELAS 1", "AKTIF", "SMP"),
  ("MP017", "Pendidikan Kewarganegaraan", "KELAS 1", "AKTIF", "SMP"),
  ("MP018", "Informatika", "KELAS 1", "AKTIF", "SMP"),
  ("MP019", "Pendidikan Jasmani dan Kesehatan", "KELAS 1", "AKTIF", "SMP"),
  ("MP020", "Seni Budaya", "KELAS 1", "AKTIF", "SMP"),
  ("MP021", "Bahasa Sunda", "KELAS 1", "AKTIF", "SMP"),
  ("MP022", "21", "KELAS 1", "AKTIF", "SMP"),
  ("MP023", "Tamrin Lughoh", "KELAS 2", "AKTIF", "SMP"),
  ("MP024", "Nahwu", "KELAS 2", "AKTIF", "SMP"),
  ("MP025", "Mutholaah", "KELAS 2", "AKTIF", "SMP"),
  ("MP026", "Aqidah", "KELAS 2", "AKTIF", "SMP"),
  ("MP027", "Hadist", "KELAS 2", "AKTIF", "SMP"),
  ("MP028", "Fiqih", "KELAS 2", "AKTIF", "SMP"),
  ("MP029", "Tarikh Islam", "KELAS 2", "AKTIF", "SMP"),
  ("MP030", "Tajwid", "KELAS 2", "AKTIF", "SMP"),
  ("MP031", "Imla", "KELAS 2", "AKTIF", "SMP"),
  ("MP032", "Khot", "KELAS 2", "AKTIF", "SMP"),
  ("MP033", "Mahfudzot", "KELAS 2", "AKTIF", "SMP"),
  ("MP034", "Pendidikan Agama Islam", "KELAS 2", "AKTIF", "SMP"),
  ("MP035", "Bahasa Indonesia", "KELAS 2", "AKTIF", "SMP"),
  ("MP036", "Bahasa Inggris", "KELAS 2", "AKTIF", "SMP"),
  ("MP037", "Matematika", "KELAS 2", "AKTIF", "SMP"),
  ("MP038", "Ilmu Pengetahuan Alam", "KELAS 2", "AKTIF", "SMP"),
  ("MP039", "Ilmu Pengetahuan Sosial", "KELAS 2", "AKTIF", "SMP"),
  ("MP040", "Pendidikan Kewarganegaraan", "KELAS 2", "AKTIF", "SMP"),
  ("MP041", "Informatika", "KELAS 2", "AKTIF", "SMP"),
  ("MP042", "Pendidikan Jasmani dan Kesehatan", "KELAS 2", "AKTIF", "SMP"),
  ("MP043", "Seni Budaya", "KELAS 2", "AKTIF", "SMP"),
  ("MP044", "Bahasa Sunda", "KELAS 2", "AKTIF", "SMP"),
  ("MP045", "22", "KELAS 2", "AKTIF", "SMP"),
  ("MP046", "Tamrin Lughoh", "KELAS 3", "AKTIF", "SMP"),
  ("MP047", "Nahwu", "KELAS 3", "AKTIF", "SMP"),
  ("MP048", "Shorof", "KELAS 3", "AKTIF", "SMP"),
  ("MP049", "Muthola'ah", "KELAS 3", "AKTIF", "SMP"),
  ("MP050", "Insya", "KELAS 3", "AKTIF", "SMP"),
  ("MP051", "Hadist", "KELAS 3", "AKTIF", "SMP"),
  ("MP052", "Fiqih", "KELAS 3", "AKTIF", "SMP"),
  ("MP053", "Faroid", "KELAS 3", "AKTIF", "SMP"),
  ("MP054", "Imla", "KELAS 3", "AKTIF", "SMP"),
  ("MP055", "Khot", "KELAS 3", "AKTIF", "SMP"),
  ("MP056", "Pendidikan Agama Islam", "KELAS 3", "AKTIF", "SMP"),
  ("MP057", "Bahasa Indonesia", "KELAS 3", "AKTIF", "SMP"),
  ("MP058", "Bahasa Inggris", "KELAS 3", "AKTIF", "SMP"),
  ("MP059", "Matematika", "KELAS 3", "AKTIF", "SMP"),
  ("MP060", "Ilmu Pengetahuan Alam", "KELAS 3", "AKTIF", "SMP"),
  ("MP061", "Ilmu Pengetahuan Sosial", "KELAS 3", "AKTIF", "SMP"),
  ("MP062", "Pendidikan Kewarganegaraan", "KELAS 3", "AKTIF", "SMP"),
  ("MP063", "Informatika", "KELAS 3", "AKTIF", "SMP"),
  ("MP064", "Pendidikan Jasmani dan Kesehatan", "KELAS 3", "AKTIF", "SMP"),
  ("MP065", "Seni Budaya", "KELAS 3", "AKTIF", "SMP"),
  ("MP066", "Bahasa Sunda", "KELAS 3", "AKTIF", "SMP"),
  ("MP067", "21", "KELAS 3", "AKTIF", "SMP"),
  ("MP068", "Tamrin Lughoh", "KELAS 4", "AKTIF", "SMA"),
  ("MP069", "Nahwu", "KELAS 4", "AKTIF", "SMA"),
  ("MP070", "Shorof", "KELAS 4", "AKTIF", "SMA"),
  ("MP071", "Muthola'ah", "KELAS 4", "AKTIF", "SMA"),
  ("MP072", "Insya", "KELAS 4", "AKTIF", "SMA"),
  ("MP073", "Tafsir", "KELAS 4", "AKTIF", "SMA"),
  ("MP074", "Tarbiyah", "KELAS 4", "AKTIF", "SMA"),
  ("MP075", "Grammar", "KELAS 4", "AKTIF", "SMA"),
  ("MP076", "Hadist", "KELAS 4", "AKTIF", "SMA"),
  ("MP077", "Fiqih", "KELAS 4", "AKTIF", "SMA"),
  ("MP078", "Ushul Fiqh", "KELAS 4", "AKTIF", "SMA"),
  ("MP079", "Pendidikan Agama Islam", "KELAS 4", "AKTIF", "SMA"),
  ("MP080", "Bahasa Indonesia", "KELAS 4", "AKTIF", "SMA"),
  ("MP081", "Bahasa Inggris", "KELAS 4", "AKTIF", "SMA"),
  ("MP082", "Matematika", "KELAS 4", "AKTIF", "SMA"),
  ("MP083", "Fisika", "KELAS 4", "AKTIF", "SMA"),
  ("MP084", "Kimia", "KELAS 4", "AKTIF", "SMA"),
  ("MP085", "Biologi", "KELAS 4", "AKTIF", "SMA"),
  ("MP086", "Ekonomi", "KELAS 4", "AKTIF", "SMA"),
  ("MP087", "Geografi", "KELAS 4", "AKTIF", "SMA"),
  ("MP088", "Sosiologi", "KELAS 4", "AKTIF", "SMA"),
  ("MP089", "Pendidikan Kewarganegaraan", "KELAS 4", "AKTIF", "SMA"),
  ("MP090", "Sejarah", "KELAS 4", "AKTIF", "SMA"),
  ("MP091", "Pendidikan Jasmani dan Kesehatan", "KELAS 4", "AKTIF", "SMA"),
  ("MP092", "Life Skill", "KELAS 4", "AKTIF", "SMA"),
  ("MP093", "Bahasa Sunda", "KELAS 4", "AKTIF", "SMA"),
  ("MP094", "26", "KELAS 4", "AKTIF", "SMA"),
  ("MP095", "Insya", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP096", "Nahwu", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP097", "Shorof", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP098", "Muthola'ah", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP099", "Tafsir", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP100", "Tarbiyah", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP101", "Grammar", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP102", "Hadist", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP103", "Mustholahul Hadist", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP104", "Fiqih", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP105", "Ushul Fiqh", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP106", "Pendidikan Agama Islam", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP107", "Bahasa Indonesia", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP108", "Bahasa Inggris", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP109", "Matematika", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP110", "Matematika Tingkat Lanjut", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP111", "Fisika", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP112", "Kimia", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP113", "Biologi", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP114", "Pendidikan Kewarganegaraan", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP115", "Sejarah", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP116", "Pendidikan Jasmani dan Kesehatan", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP117", "Informatika", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP118", "Life Skill", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP119", "Bahasa Sunda", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP120", "25", "KELAS 5-IPA", "AKTIF", "SMA"),
  ("MP121", "Insya", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP122", "Nahwu", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP123", "Shorof", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP124", "Muthola'ah", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP125", "Tafsir", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP126", "Tarbiyah", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP127", "Grammar", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP128", "Hadist", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP129", "Mustholahul Hadist", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP130", "Fiqih", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP131", "Ushul Fiqh", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP132", "Pendidikan Agama Islam", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP133", "Bahasa Indonesia", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP134", "Bahasa Inggris", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP135", "Matematika", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP136", "Antropologi", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP137", "Ekonomi", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP138", "Geografi", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP139", "Sosiologi", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP140", "Pendidikan Kewarganegaraan", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP141", "Sejarah", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP142", "Pendidikan Jasmani dan Kesehatan", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP143", "Informatika", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP144", "Life Skill", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP145", "Bahasa Sunda", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP146", "25", "KELAS 5-IPS", "AKTIF", "SMA"),
  ("MP147", "Insya", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP148", "Nahwu", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP149", "Shorof", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP150", "Muthola'ah", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP151", "Tafsir", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP152", "Tarbiyah", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP153", "Grammar", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP154", "Balagoh", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP155", "Ulumul Qur'an", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP156", "Fiqih", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP157", "Ushul Fiqh", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP158", "Pendidikan Agama Islam", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP159", "Bahasa Indonesia", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP160", "Bahasa Inggris", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP161", "Matematika", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP162", "Matematika Tingkat Lanjut", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP163", "Fisika", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP164", "Kimia", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP165", "Biologi", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP166", "Pendidikan Kewarganegaraan", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP167", "Sejarah", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP168", "Pendidikan Jasmani dan Kesehatan", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP169", "Informatika", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP170", "Life Skill", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP171", "Bahasa Sunda", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP172", "25", "KELAS 6-IPA", "AKTIF", "SMA"),
  ("MP173", "Insya", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP174", "Nahwu", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP175", "Shorof", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP176", "Muthola'ah", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP177", "Tafsir", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP178", "Tarbiyah", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP179", "Grammar", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP180", "Balagoh", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP181", "Ulumul Qur'an", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP182", "Fiqih", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP183", "Ushul Fiqh", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP184", "Pendidikan Agama Islam", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP185", "Bahasa Indonesia", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP186", "Bahasa Inggris", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP187", "Matematika", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP188", "Antropologi", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP189", "Ekonomi", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP190", "Geografi", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP191", "Sosiologi", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP192", "Pendidikan Kewarganegaraan", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP193", "Sejarah", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP194", "Pendidikan Jasmani dan Kesehatan", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP195", "Informatika", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP196", "Life Skill", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP197", "Bahasa Sunda", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP198", "25", "KELAS 6-IPS", "AKTIF", "SMA"),
  ("MP199", "Tamrin Lughoh", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP200", "Mutholaah", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP201", "Aqidah", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP202", "Hadist", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP203", "Fiqih", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP204", "Tarikh Islam", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP205", "Tajwid", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP206", "Imla", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP207", "Khot", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP208", "Mahfudzot", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP209", "Pendidikan Agama Islam", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP210", "Bahasa Indonesia", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP211", "Bahasa Inggris", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP212", "Matematika", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP213", "Fisika", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP214", "Kimia", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP215", "Biologi", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP216", "Ekonomi", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP217", "Geografi", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP218", "Sosiologi", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP219", "Pendidikan Kewarganegaraan", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP220", "Sejarah", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP221", "Pendidikan Jasmani dan Kesehatan", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP222", "Life Skill", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP223", "Bahasa Sunda", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP224", "25", "KELAS 1INT", "AKTIF", "SMA"),
  ("MP225", "Tamrin Lughoh", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP226", "Nahwu", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP227", "Shorof", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP228", "Muthola'ah", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP229", "Insya", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP230", "Tafsir", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP231", "Tarbiyah", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP232", "Grammar", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP233", "Hadist", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP234", "Fiqih", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP235", "Imla", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP236", "Pendidikan Agama Islam", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP237", "Bahasa Indonesia", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP238", "Bahasa Inggris", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP239", "Matematika", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP240", "Matematika Tingkat Lanjut", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP241", "Fisika", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP242", "Kimia", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP243", "Biologi", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP244", "Pendidikan Kewarganegaraan", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP245", "Sejarah", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP246", "Pendidikan Jasmani dan Kesehatan", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP247", "Informatika", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP248", "Life Skill", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP249", "Bahasa Sunda", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP250", "25", "KELAS 2INT-IPA", "AKTIF", "SMA"),
  ("MP251", "Tamrin Lughoh", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP252", "Nahwu", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP253", "Shorof", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP254", "Muthola'ah", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP255", "Insya", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP256", "Tafsir", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP257", "Tarbiyah", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP258", "Grammar", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP259", "Hadist", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP260", "Fiqih", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP261", "Imla", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP262", "Pendidikan Agama Islam", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP263", "Bahasa Indonesia", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP264", "Bahasa Inggris", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP265", "Matematika", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP266", "Antropologi", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP267", "Ekonomi", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP268", "Geografi", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP269", "Sosiologi", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP270", "Pendidikan Kewarganegaraan", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP271", "Sejarah", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP272", "Pendidikan Jasmani dan Kesehatan", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP273", "Informatika", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP274", "Life Skill", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP275", "Bahasa Sunda", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP276", "25", "KELAS 2INT-IPS", "AKTIF", "SMA"),
  ("MP277", "Insya", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP278", "Nahwu", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP279", "Shorof", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP280", "Muthola'ah", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP281", "Tafsir", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP282", "Tarbiyah", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP283", "Grammar", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP284", "Mustholahul Hadist", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP285", "Ulumul Qur'an", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP286", "Fiqih", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP287", "Ushul Fiqh", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP288", "Pendidikan Agama Islam", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP289", "Bahasa Indonesia", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP290", "Bahasa Inggris", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP291", "Matematika", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP292", "Matematika Tingkat Lanjut", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP293", "Fisika", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP294", "Kimia", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP295", "Biologi", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP296", "Pendidikan Kewarganegaraan", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP297", "Sejarah", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP298", "Pendidikan Jasmani dan Kesehatan", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP299", "Informatika", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP300", "Life Skill", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP301", "Bahasa Sunda", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP302", "25", "KELAS 3INT-IPA", "AKTIF", "SMA"),
  ("MP303", "Insya", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP304", "Nahwu", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP305", "Shorof", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP306", "Muthola'ah", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP307", "Tafsir", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP308", "Tarbiyah", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP309", "Grammar", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP310", "Mustholahul Hadist", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP311", "Ulumul Qur'an", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP312", "Fiqih", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP313", "Ushul Fiqh", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP314", "Pendidikan Agama Islam", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP315", "Bahasa Indonesia", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP316", "Bahasa Inggris", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP317", "Matematika", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP318", "Antropologi", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP319", "Ekonomi", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP320", "Geografi", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP321", "Sosiologi", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP322", "Pendidikan Kewarganegaraan", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP323", "Sejarah", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP324", "Pendidikan Jasmani dan Kesehatan", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP325", "Informatika", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP326", "Life Skill", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP327", "Bahasa Sunda", "KELAS 3INT-IPS", "AKTIF", "SMA"),
  ("MP328", "25", "KELAS 3INT-IPS", "AKTIF", "SMA")
]
